version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
version: 1
update_configs:
  # Keep package.json up to date as soon as
  # new versions are published to the npm registry
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'weekly'
    default_reviewers:
      - 'Shopify/platform-dev-tools-education'
    version_requirement_updates: 'auto'
